version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./public:/code/public
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
  php:
   image: php:8.1-fpm
   volumes:
     - ./:/code

  cli:
    build:
      context: .
      dockerfile: docker/php-cli/Dockerfile
    volumes:
      - ./:/code

