version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./public:/code/public
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - internal
  php:
   image: php:8.1-fpm
   volumes:
     - ./:/code
   networks:
     - internal

  cli:
    build:
      context: .
      dockerfile: docker/php-cli/Dockerfile
    volumes:
      - ./:/code
networks:
  internal:
    driver: bridge

